google.maps.__gjsload__('map', function(_){var sv=function(){var a=_.ae();return _.Ac(a,16)},tv=function(a){for(var b=_.Hc(a,0),c=[],d=0;d<b;d++)c.push(a.getUrl(d));return c},uv=function(a,b){a=tv(new _.Td(a.o.V[7]));return _.im(a,function(c){return c+"deg="+b+"&"})},vv=function(a,b){return b?(a=a.i[b])?_.Ac(a,4)||0:0:0},wv=function(a,b){if(!b)return null;a=a.i[b];if(!a||!_.Hc(a,6))return null;b=[];for(var c=0;c<_.Hc(a,6);c++)b.push(_.Ec(a,6,c));return b},xv=function(a,b){if(!b)return null;a=a.i[b];if(!a||!_.Hc(a,5))return null;b=[];for(var c=
0;c<_.Hc(a,5);c++)b.push(_.Ec(a,5,c));return b},yv=function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return e;return-1},zv=function(a){if(!(a.W&&a.H&&a.i&&a.o&&a.j))return null;if(a.i.i){var b=a.i.i.i(a.H,a.o,_.Vm(a.i),a.i.tilt,a.i.heading,a.j);var c=new _.O(-b[0],-b[1]);a=new _.O(a.j.wa-b[0],a.j.Aa-b[1])}else c=_.Um(a.i,_.Om(a.W.min,a.H)),a=_.Um(a.i,_.Om(a.W.max,a.H)),c=new _.O(c.wa,c.Aa),a=new _.O(a.wa,a.Aa);return new _.sg([c,a])},
Av=function(a){_.D(this,a,4)},Bv=function(){this.Ga=new _.Vf},Cv=function(a){_.Zf(a.Ga,function(b){b(null)})},Dv=function(a,b){if(_.Gu)return new MouseEvent(a,{bubbles:!0,cancelable:!0,view:window,detail:1,screenX:b.clientX,screenY:b.clientY,clientX:b.clientX,clientY:b.clientY});var c=document.createEvent("MouseEvents");c.initMouseEvent(a,!0,!0,window,1,b.clientX,b.clientY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);return c},Ev=function(a,b,c){this.i=a;this.o=b;this.j=c},Gv=function(a,b,c,d){var e=this;
this.H=b;this.$=c;this.W=d;this.o=null;this.j=this.i=0;this.T=new _.gn(function(){e.i=0;e.j=0},1E3);new _.Mp(a,"wheel",function(f){return Fv(e,f)})},Fv=function(a,b){if(!_.Im(b)){var c=a.W();if(0!=c){var d=null==c&&!b.ctrlKey&&!b.altKey&&!b.metaKey&&!b.buttons;c=a.$(d?1:4);if("none"!=c&&("cooperative"!=c||!d))if(_.ef(b),d=(b.deltaY||b.wheelDelta||0)*(1==b.deltaMode?16:1),0<d&&d<a.j||0>d&&d>a.j)a.j=d;else{a.j=d;a.i+=d;a.T.Ob();var e=a.H.i.i;16>Math.abs(a.i)||(d=Math.round(e.zoom-Math.sign(a.i)),a.i=
0,b="zoomaroundcenter"==c?e.center:a.H.Tc(b),a.o!=d&&(Hv(a.H,d,b,function(){a.o=null}),a.o=d))}}}},Iv=function(a,b,c){this.o=a;this.H=b;this.j=c||null;this.i=null},Jv=function(a,b,c,d){this.j=a;this.H=b;this.T=c;this.o=d||null;this.i=null},Kv=function(a,b){return{Gb:a.j.Tc(b.Gb),radius:b.radius,zoom:a.j.i.i.zoom}},Lv=function(a,b,c,d,e){d=void 0===d?_.p("greedy"):d;var f=void 0===e?{}:e;e=void 0===f.ii?_.p(!0):f.ii;var g=void 0===f.Ek?!1:f.Ek,h=void 0===f.hj?_.p(null):f.hj;f={Yf:void 0===f.Yf?!1:
f.Yf,onClick:function(m){var q=m.coords,r=m.event;m.Nd&&(r=3==r.button,l.j()&&(m=l.o(4),"none"!=m&&(r=Math.round(l.i.i.i.zoom+(r?-1:1)),q="zoomaroundcenter"==m?l.i.i.i.center:l.i.Tc(q),Hv(l.i,r,q))))}};var k=_.fq(b.o,f);new Gv(b.o,a,d,h);var l=new Ev(a,d,e);f.Jd=new Jv(a,d,k,c);g&&(f.Dk=new Iv(a,k,c));return k},Mv=function(){var a=window.innerWidth/(document.body.scrollWidth+1);return.95>window.innerHeight/(document.body.scrollHeight+1)||.95>a||_.Vo()},Nv=function(a,b,c,d){return 0==b?"none":"none"==
c||"greedy"==c||"zoomaroundcenter"==c?c:d?"greedy":"cooperative"==c||a()?"cooperative":"greedy"},Ov=function(a){return new _.kr([a.draggable,a.xk,a.Cf],_.hm(Nv,Mv))},Pv=function(a){this.i=new Bv;this.j=a},Qv=function(a,b){return(a.get("featureRects")||[]).some(function(c){return c.contains(b)})},Rv=function(a,b){if(!b)return 0;var c=0,d=a.Za,e=a.Va;b=_.Aa(b);for(var f=b.next();!f.done;f=b.next()){var g=f.value;if(a.intersects(g)){f=g.Za;var h=g.Va;if(_.Mm(g,a))return 1;g=e.contains(h.i)&&h.contains(e.i)&&
!e.equals(h)?_.sf(h.i,e.j)+_.sf(e.i,h.j):_.sf(e.contains(h.i)?h.i:e.i,e.contains(h.j)?h.j:e.j);c+=g*(Math.min(d.j,f.j)-Math.max(d.i,f.i))}}return c/=(d.isEmpty()?0:d.j-d.i)*_.tf(e)},Sv=function(){return function(a,b){if(a&&b)return.9<=Rv(a,b)}},Tv=function(){var a=!1;return function(b,c){if(b&&c){if(.999999>Rv(b,c))return a=!1;b=_.so(b,(_.Qu-1)/2);return.999999<Rv(b,c)?a=!0:a}}},Uv=function(a,b){var c=null;a&&a.some(function(d){(d=d.vf(b))&&68===d.getType()&&(c=d);return!!c});return c},Vv=function(a,
b,c,d,e,f,g,h){var k=new _.vt;_.wt(k,a,b,"hybrid"!=c);null!=c&&_.yt(k,c,0,d);g&&g.forEach(function(l){return _.At(k,l,c,!1)});e&&_.B(e,function(l){return _.zt(k,l)});f&&_.tt(f,_.Ws(_.qt(k.i)));h&&_.Ct(k,h);return k.i},Wv=function(a,b,c,d,e,f,g,h,k,l){var m=[],q=null,r=Uv(k,c);if(r)q=r;else if(e&&(q=new _.zn,q.V[0]=e.type,e.params))for(var u in e.params){r=_.An(q);_.yn(r,u);var v=e.params[u];v&&(r.V[1]=v)}(e=q)&&m.push(e);e=new _.zn;e.V[0]=37;_.yn(_.An(e),"smartmaps");m.push(e);return{jc:Vv(a,b,c,
d,m,f,k,l),Yc:g,scale:h}},Xv=function(a,b,c,d,e,f,g,h,k,l,m,q,r,u,v){this.T=a;this.o=b;this.projection=c;this.maxZoom=d;this.tileSize=new _.P(256,256);this.name=e;this.alt=f;this.ha=g;this.heading=u;this.ma=_.le(u);this.De=h;this.__gmsd=k;this.mapTypeId=l;this.ua=void 0===v?!1:v;this.i=null;this.$=m;this.H=q;this.W=r;this.triggersTileLoadEvent=!0;this.j=_.xg({})},Yv=function(a,b,c,d,e,f){Xv.call(this,a.T,a.o,a.projection,a.maxZoom,a.name,a.alt,a.ha,a.De,a.__gmsd,a.mapTypeId,a.$,a.H,a.W,a.heading,
a.ua);this.o&&this.j.set(Wv(this.H,this.W,this.mapTypeId,this.$,this.__gmsd,b,c,d,e,f))},Zv=function(a,b,c){var d=document.createElement("div"),e=document.createElement("div"),f=document.createElement("span");f.innerText="For development purposes only";f.style.j="break-all";e.appendChild(f);f=e.style;f.color="white";f.fontFamily="Roboto, sans-serif";f.fontSize="14px";f.textAlign="center";f.position="absolute";f.left="0";f.top="50%";f.transform="translateY(-50%)";f.msTransform="translateY(-50%)";f.maxHeight=
"100%";f.width="100%";f.overflow="hidden";d.appendChild(e);e=d.style;e.backgroundColor="rgba(0, 0, 0, 0.5)";e.position="absolute";e.overflow="hidden";e.top="0";e.left="0";e.width=b+"px";e.height=c+"px";e.zIndex=100;a.appendChild(d)},$v=function(a,b,c,d,e){e=void 0===e?{}:e;this.i=a;this.j=b.slice(0);this.o=e.Mb||_.La;this.loaded=Promise.all(b.map(function(f){return f.loaded})).then(_.n());d&&Zv(this.i,c.wa,c.Aa)},aw=function(a,b){this.Wa=a[0].Wa;this.i=a;this.Wb=a[0].Wb;this.j=void 0===b?!1:b},cw=
function(a,b,c,d,e,f,g,h){var k=this;this.j=a;this.$=_.im(b||[],function(l){return l.replace(/&$/,"")});this.ma=c;this.ha=d;this.i=e;this.W=f;this.o=g;this.loaded=new Promise(function(l){k.T=l});this.H=!1;h&&(a=this.Eb(),Zv(a,f.size.wa,f.size.Aa));bw(this)},bw=function(a){var b=a.j.Xa,c=b.Ea,d=b.Fa,e=b.La;if(a.o&&(b=_.Rn(_.bn(a.W,{Ea:c+.5,Fa:d+.5,La:e}),null),!Qv(a.o,b))){a.H=!0;a.o.i.addListenerOnce(function(){return bw(a)});return}a.H=!1;b=2==a.i||4==a.i?a.i:1;b=Math.min(1<<e,b);for(var f=a.ma&&
4!=b,g=e,h=b;1<h;h/=2)g--;(c=a.ha({Ea:c,Fa:d,La:e}))?(c=_.np(_.np(_.np(new _.hp(_.Dt(a.$,c)),"x",c.Ea),"y",c.Fa),"z",g),1!=b&&_.np(c,"w",a.W.size.wa/b),f&&(b*=2),1!=b&&_.np(c,"scale",b),a.j.setUrl(c.toString()).then(a.T)):a.j.setUrl("").then(a.T)},dw=function(a,b,c,d,e,f,g,h){this.j=a||[];this.$=new _.P(e.size.wa,e.size.Aa);this.ha=b;this.o=c;this.i=d;this.Wb=1;this.Wa=e;this.H=f;this.T=void 0===g?!1:g;this.W=h},ew=function(a,b){this.j=a;this.i=b;this.Wa=_.sl;this.Wb=1},fw=function(a,b,c,d,e,f,g){this.j=
void 0===g?!1:g;this.i=e;this.H=new _.qh;this.o=_.Pd(c);this.T=_.F(c,1);this.$=_.Ac(b,14);this.W=_.Ac(b,15);this.ha=new _.Oh(a,b,c);this.ua=f;this.ma=function(){_.Cj(d,"Sni")}},gw=function(a,b,c,d){d=void 0===d?{kc:null}:d;var e=_.le(d.heading),f=("hybrid"==b&&!e||"terrain"==b||"roadmap"==b)&&0!=d.mk,g=d.kc;if("satellite"==b){var h;e?h=uv(a.ha,d.heading||0):h=tv(new _.Td(a.ha.o.V[1]));b=new _.uh({wa:256,Aa:256},e?45:0,d.heading||0);return new dw(h,f&&1<_.to(),_.Lt(d.heading),g&&g.scale||null,b,e?
a.ua:null,!!d.$h,a.ma)}return new _.Kt(_.dn(a.ha),"Przepraszamy, nie mamy zdj\u0119\u0107 tego miejsca.",f&&1<_.to(),_.Lt(d.heading),c,g,d.heading,a.ma)},hw=function(a){function b(c,d){if(!d||!d.jc)return d;var e=new _.Zs(_.Jc(d.jc));_.Ws(_.qt(e)).V[0]=c;return{scale:d.scale,Yc:d.Yc,jc:e}}return function(c){var d=gw(a,"roadmap",a.i,{mk:!1,kc:b(3,c.kc().get())}),e=gw(a,"roadmap",a.i,{kc:b(18,c.kc().get())});d=new aw([d,e]);c=gw(a,"roadmap",a.i,{kc:c.kc().get()});return new ew(d,c)}},iw=function(a){return function(b,
c){var d=b.kc().get(),e=gw(a,"satellite",null,{heading:b.heading,kc:d,$h:!1});b=gw(a,"hybrid",a.i,{heading:b.heading,kc:d});return new aw([e,b],c)}},jw=function(a,b){return new Xv(iw(a),a.i,"number"===typeof b?new _.On(b):a.H,"number"===typeof b?21:22,"Hybryda","Poka\u017c zdj\u0119cia z nazwami ulic",_.uu.hybrid,"m@"+a.$,{type:68,params:{set:"RoadmapSatellite"}},"hybrid",a.W,a.o,a.T,b,a.j)},kw=function(a){return function(b,c){return gw(a,"satellite",null,{heading:b.heading,kc:b.kc().get(),$h:c})}},
lw=function(a,b){var c="number"===typeof b;return new Xv(kw(a),null,"number"===typeof b?new _.On(b):a.H,c?21:22,"Satelita","Poka\u017c zdj\u0119cia satelitarne",c?"a":_.uu.satellite,null,null,"satellite",a.W,a.o,a.T,b,a.j)},mw=function(a,b){return function(c){return gw(a,b,a.i,{kc:c.kc().get()})}},nw=function(a,b,c){c=void 0===c?{}:c;var d=[0,90,180,270];if("hybrid"==b)for(b=jw(a),b.i={},d=_.Aa(d),c=d.next();!c.done;c=d.next())c=c.value,b.i[c]=jw(a,c);else if("satellite"==b)for(b=lw(a),b.i={},d=_.Aa(d),
c=d.next();!c.done;c=d.next())c=c.value,b.i[c]=lw(a,c);else b="roadmap"==b&&1<_.to()&&c.Gk?new Xv(hw(a),a.i,a.H,22,"Mapa","Poka\u017c map\u0119 ulic",_.uu.roadmap,"m@"+a.$,{type:68,params:{set:"Roadmap"}},"roadmap",a.W,a.o,a.T,void 0,a.j):"terrain"==b?new Xv(mw(a,"terrain"),a.i,a.H,21,"Teren","Poka\u017c map\u0119 ulic z terenem",_.uu.terrain,"r@"+a.$,{type:68,params:{set:"Terrain"}},"terrain",a.W,a.o,a.T,void 0,a.j):new Xv(mw(a,"roadmap"),a.i,a.H,22,"Mapa","Poka\u017c map\u0119 ulic",_.uu.roadmap,
"m@"+a.$,{type:68,params:{set:"Roadmap"}},"roadmap",a.W,a.o,a.T,void 0,a.j);return b},ow=function(a){this.i=a;this.j=_.Qo("p",a);this.H=0;_.Jo(a,"gm-style-pbc");_.Jo(this.j,"gm-style-pbt");_.$m(_.Pu,a);a.style.transitionDuration="0";a.style.opacity=0;_.To(a)},pw=function(a,b){var c=2==_.yj.i?"Naci\u015bnij\u00a0\u2318 i przewi\u0144, by przybli\u017cy\u0107 map\u0119":"Naci\u015bnij CTRL i przewi\u0144, by przybli\u017cy\u0107 map\u0119";a.j.textContent=(void 0===b?0:b)?c:"Przesu\u0144 map\u0119 dwoma palcami";
a.i.style.transitionDuration="0.3s";a.i.style.opacity=1},qw=function(a){a.i.style.transitionDuration="0.8s";a.i.style.opacity=0},tw=function(a,b,c,d){var e=this;this.i=a;this.T=b;this.$=c.o;this.W=d;this.H=0;this.o=null;this.j=!1;_.fq(c.T,{Ib:function(f){return rw(e,"mousedown",f.coords,f.Ta)},yd:function(f){e.T.i.j||(e.o=f,5<(0,_.nc)()-e.H&&sw(e))},Nb:function(f){return rw(e,"mouseup",f.coords,f.Ta)},onClick:function(f){var g=f.coords,h=f.event;f=f.Nd;3==h.button?f||rw(e,"rightclick",g,h.Ta):f?rw(e,
"dblclick",g,h.Ta,Dv("dblclick",g)):rw(e,"click",g,h.Ta,Dv("click",g))},Jd:{xd:function(f,g){e.j||(e.j=!0,rw(e,"dragstart",f.Gb,g.Ta))},qe:function(f){rw(e,e.j?"drag":"mousemove",f.Gb)},Pd:function(f){e.j&&(e.j=!1,rw(e,"dragend",f))}}}).Rd(!0);new _.Ot(c.o,c.T,{Ve:function(f){return rw(e,"mouseout",f,f)},We:function(f){return rw(e,"mouseover",f,f)}})},sw=function(a){if(a.o){var b=a.o;uw(a,"mousemove",b.coords,b.Ta);a.o=null;a.H=(0,_.nc)()}},rw=function(a,b,c,d,e){sw(a);uw(a,b,c,d,e)},uw=function(a,
b,c,d,e){var f=e||d,g=a.T.Tc(c),h=_.Rn(g,a.i.getProjection()),k=a.$.getBoundingClientRect();c=new _.wn(h,f,new _.O(c.clientX-k.left,c.clientY-k.top),new _.O(g.Ca,g.Da));f=!!d&&!!d.touches;g=!!d&&"touch"==d.pointerType;h=!!d&&!!window.MSPointerEvent&&d.pointerType==window.MSPointerEvent.MSPOINTER_TYPE_TOUCH;k=a.i.__gm.o;var l=b,m=k.H,q=c.ub&&_.Im(c.ub);if(k.i){var r=k.i;var u=k.j}else if("mouseout"==l||q)u=r=null;else{for(var v=0;r=m[v++];){var x=c.ab,w=c.latLng;(u=r.o(c,!1))&&!r.j(l,u)&&(u=null,c.ab=
x,c.latLng=w);if(u)break}if(!u&&(f||g||h))for(v=0;(r=m[v++])&&(x=c.ab,w=c.latLng,(u=r.o(c,!0))&&!r.j(l,u)&&(u=null,c.ab=x,c.latLng=w),!u););}if(r!=k.o||u!=k.T)k.o&&k.o.handleEvent("mouseout",c,k.T),k.o=r,k.T=u,r&&r.handleEvent("mouseover",c,u);r?"mouseover"==l||"mouseout"==l?u=!1:(r.handleEvent(l,c,u),u=!0):u=!!q;if(u)d&&e&&_.Im(e)&&_.gf(d);else{a.i.__gm.set("cursor",a.i.get("draggableCursor"));"dragstart"!=b&&"drag"!=b&&"dragend"!=b||_.L.trigger(a.i.__gm,b,c);if("none"==a.W.get()){if("dragstart"==
b||"dragend"==b)return;"drag"==b&&(b="mousemove")}"dragstart"==b||"drag"==b||"dragend"==b?_.L.trigger(a.i,b):_.L.trigger(a.i,b,c)}},Bw=function(a,b,c,d,e,f){var g=vw,h=this;this.$=a;this.W=b;this.j=c;this.T=d;this.H=g;e.addListener(function(){return ww(h)});f.addListener(function(){return ww(h)});this.o=f;this.i=[];_.L.addListener(c,"insert_at",function(k){xw(h,k)});_.L.addListener(c,"remove_at",function(k){var l=h.i[k];l&&(h.i.splice(k,1),yw(h),l.clear())});_.L.addListener(c,"set_at",function(k){var l=
h.j.getAt(k);zw(h,l);k=h.i[k];(l=Aw(h,l))?_.Vt(k,l):k.clear()});this.j.forEach(function(k,l){xw(h,l)})},ww=function(a){for(var b=a.i.length,c=0;c<b;++c)_.Vt(a.i[c],Aw(a,a.j.getAt(c)))},xw=function(a,b){var c=a.j.getAt(b);zw(a,c);var d=a.H(a.W,b,a.T,function(e){var f=a.j.getAt(b);!e&&f&&_.L.trigger(f,"tilesloaded")});_.Vt(d,Aw(a,c));a.i.splice(b,0,d);yw(a,b)},yw=function(a,b){for(var c=0;c<a.i.length;++c)c!=b&&a.i[c].setZIndex(c)},zw=function(a,b){if(b){var c="Oto";switch(b.mapTypeId){case "roadmap":c=
"Otm";break;case "satellite":c="Otk";break;case "hybrid":c="Oth";break;case "terrain":c="Otr"}b instanceof _.nj&&(c="Ots");a.$(c)}},Aw=function(a,b){return b?b instanceof _.kj?b.Pb(a.o.get()):new _.St(b):null},vw=function(a,b,c,d){return new _.Tt(function(e,f){e=new _.go(a,b,c,_.ao(e),f,{Pe:!0});c.yc(e);return e},d)},Cw=function(a,b){this.j=a;this.T=b},Dw=function(a,b,c,d,e){return d?new Cw(a,function(){return e}):_.xh[23]?new Cw(a,function(f){var g=c.get("scale");return 2==g||4==g?b:f}):a},Ew=function(){var a=
null,b=null,c=!1;return function(d,e,f){if(f)return null;if(b==d&&c==e)return a;b=d;c=e;a=null;d instanceof _.kj?a=d.Pb(e):d&&(a=new _.St(d));return a}},Fw=function(a,b,c,d,e){this.o=a;d=_.nr(this,"apistyle");var f=_.nr(this,"authUser"),g=_.nr(this,"baseMapType"),h=_.nr(this,"scale"),k=_.nr(this,"tilt");a=_.nr(this,"blockingLayerCount");this.i=null;var l=(0,_.y)(this.rk,this);b=new _.kr([d,f,b,g,h,k,e],l);_.mr(this,"tileMapType",b);this.H=new _.kr([b,c,a],Ew())},Gw=function(a,b){var c=a.__gm;b=new Fw(a.mapTypes,
c.j,b,_.hm(_.Cj,a),c.va);b.bindTo("heading",a);b.bindTo("mapTypeId",a);_.xh[23]&&b.bindTo("scale",a);b.bindTo("apistyle",c);b.bindTo("authUser",c);b.bindTo("tilt",c);b.bindTo("blockingLayerCount",c);return b},Hw=_.n(),Iw=function(a,b){var c=xv(b,a)||void 0;a=wv(b,a)||void 0;if(!c&&!a)return null;if(a){var d=new _.Bq;a.forEach(function(e){_.Dc(d,0,e)})}return{paintExperimentIds:c,mi:d}},Jw=function(a,b,c,d){if(a){var e=_.Ph(b,a),f=vv(b,a);a=Iw(a,b);if(e||f||a){e&&_.Cj(c,"MIdRs");if(f){_.Cj(c,"MIdPd");
var g=new _.st;g.layerId="maps_api";g.mapsApiLayer=new _.sr([f])}a&&d.va.set(a);_.L.kb(c,"maptypeid_changed",function(){var h=d.j.get();"roadmap"===c.get("mapTypeId")?(d.set("apistyle",e||null),g&&d.j.set(_.Wm(h,g))):(d.set("apistyle",null),g&&d.j.set(h.Gc(g)))})}}},Mw=function(a,b){var c=this;this.H=!1;var d=new _.xi(function(){c.notify("bounds");Kw(c)},0);this.map=a;this.W=!1;this.j=null;this.o=function(){_.yi(d)};this.i=this.T=!1;this.rb=b(function(e,f){c.W=!0;var g=c.map.getProjection();c.j&&
f.min.equals(c.j.min)&&f.max.equals(c.j.max)||(c.j=f,c.o());if(!c.i){c.i=!0;try{var h=_.Rn(e.center,g,!0);h&&!h.equals(c.map.getCenter())&&c.map.setCenter(h);var k=Math.round(e.zoom);c.map.getZoom()!=k&&c.map.setZoom(k)}finally{c.i=!1}}});a.bindTo("bounds",this,void 0,!0);a.addListener("center_changed",function(){return Lw(c)});a.addListener("zoom_changed",function(){return Lw(c)});a.addListener("projection_changed",function(){return Lw(c)});a.addListener("tilt_changed",function(){return Lw(c)});
a.addListener("heading_changed",function(){return Lw(c)});Lw(this)},Lw=function(a){if(!a.T){a.o();var b=a.rb.i.i,c=a.map.getTilt()||0,d=!b||b.tilt!=c,e=a.map.getHeading()||0,f=!b||b.heading!=e;if(!a.i||d||f){a.T=!0;try{var g=a.map.getProjection(),h=a.map.getCenter(),k=a.map.getZoom();if(g&&h&&null!=k&&!isNaN(h.lat())&&!isNaN(h.lng())){var l=_.Qn(h,g),m=!b||b.zoom!=k||d||f;a.rb.Jf({center:l,zoom:k,tilt:c,heading:e},a.W&&m)}}finally{a.T=!1}}}},Kw=function(a){if(!a.H){a.H=!0;var b=function(){a.rb.i.j?
_.Vn(b):(a.H=!1,_.L.trigger(a.map,"idle"))};_.Vn(b)}},Sw=function(a){if(!a)return"";for(var b=[],c=_.Aa(a),d=c.next();!d.done;d=c.next()){d=d.value;var e=d.featureType,f=d.elementType,g=d.stylers;d=[];var h;(h=e)?(h=h.toLowerCase(),h=Nw.hasOwnProperty(h)?Nw[h]:Ow.hasOwnProperty(h)?Ow[h]:null):h=null;h&&d.push("s.t:"+h);null!=e&&null==h&&_.te(_.se("invalid style feature type: "+e,null));e=f&&Pw[f.toLowerCase()];(e=null!=e?e:null)&&d.push("s.e:"+e);null!=f&&null==e&&_.te(_.se("invalid style element type: "+
f,null));if(g)for(f=_.Aa(g),e=f.next();!e.done;e=f.next()){a:{g=void 0;e=e.value;for(g in e){h=e[g];var k=g&&Qw[g.toLowerCase()]||null;if(k&&(_.le(h)||_.ne(h)||_.oe(h))&&h){"color"==g&&Rw.test(h)&&(h="#ff"+h.substr(1));g="p."+k+":"+h;break a}}g=void 0}g&&d.push(g)}(d=d.join("|"))&&b.push(d)}b=b.join(",");return b.length>(_.xh[131]?12288:1E3)?(_.qe("Custom style string for "+a.toString()),""):b},Tw=_.n(),Uw=function(){this.W=new Bv;this.T={};this.j={}},Vw=function(a,b,c){b=void 0===b?-Infinity:b;c=
void 0===c?Infinity:c;return b>c?(b+c)/2:Math.max(Math.min(a,c),b)},Ww=function(a,b,c,d){this.j=a&&{min:a.min,max:a.min.Ca<=a.max.Ca?a.max:new _.ag(a.max.Ca+256,a.max.Da),hp:a.max.Ca-a.min.Ca,ip:a.max.Da-a.min.Da};var e=this.j;e&&c.width&&c.height?(a=Math.log2(c.width/(e.max.Ca-e.min.Ca)),e=Math.log2(c.height/(e.max.Da-e.min.Da)),d=Math.max(b?b.min:0,(void 0===d?0:d)?Math.max(Math.ceil(a),Math.ceil(e)):Math.min(Math.floor(a),Math.floor(e)))):d=b?b.min:0;this.i={min:d,max:Math.min(b?b.max:Infinity,
30)};this.i.max=Math.max(this.i.min,this.i.max);this.o=c},Xw=function(a,b,c){this.j=a;this.o=b;this.i=c},Yw=function(a,b,c){this.i=b;this.vb=c;this.o=b.heading+360*Math.round((c.heading-b.heading)/360);var d=a.width||1,e=a.height||1;a=new Xw(b.center.Ca/d,b.center.Da/e,.5*Math.pow(2,-b.zoom));d=new Xw(c.center.Ca/d,c.center.Da/e,.5*Math.pow(2,-c.zoom));this.j=(d.i-a.i)/a.i;this.Yb=Math.hypot(.5*Math.hypot(d.j-a.j,d.o-a.o,d.i-a.i)*(this.j?Math.log1p(this.j)/this.j:1)/a.i,.005*(c.tilt-b.tilt),.007*
(c.heading-this.o));this.Ef=[];b=this.i.zoom;if(this.i.zoom<this.vb.zoom)for(;;){b=3*Math.floor(b/3+1);if(b>=this.vb.zoom)break;this.Ef.push(Math.abs(b-this.i.zoom)/Math.abs(this.vb.zoom-this.i.zoom)*this.Yb)}else if(this.i.zoom>this.vb.zoom)for(;;){b=3*Math.ceil(b/3-1);if(b<=this.vb.zoom)break;this.Ef.push(Math.abs(b-this.i.zoom)/Math.abs(this.vb.zoom-this.i.zoom)*this.Yb)}},Zw=function(a,b){this.j=a;this.H=b;this.i=Math.PI/2/b;this.o=a/this.i},$w=function(a,b){var c=void 0===b?{}:b;b=void 0===c.Fk?
300:c.Fk;var d=void 0===c.maxDistance?Infinity:c.maxDistance,e=void 0===c.tc?_.n():c.tc;c=void 0===c.speed?1.5:c.speed;this.Kb=a;this.tc=e;this.j=new Zw(c/1E3,b);this.i=a.Yb<=d?0:-1},ax=function(a){return{Kb:{vb:a,ac:function(){return a},Ef:[],Yb:0},ac:function(){return{Zc:a,done:0}},tc:_.n()}},bx=function(a,b,c){this.va=b;this.Ba=c;this.H={};this.o=this.i=null;this.T=new _.ag(0,0);this.ha=null;this.Ka=a.o;this.$=a.i;this.W=a.j;this.ua=_.Tn();this.Ba.Hg&&(this.W.style.willChange=this.$.style.willChange=
"transform");this.ma=this.j=void 0},cx=function(a,b){return((void 0===b?0:b)?a.ha:null)||(a.ha=a.Ka.getBoundingClientRect())},dx=function(a,b,c,d){var e=b.center,f=b.heading,g=b.tilt,h=_.eg(b.zoom,g,f,a.j);a.i={center:e,scale:h};b=a.getBounds(b);e=a.T=_.fg(h,_.Tm(_.Um(h,e)));a.o={wa:0,Aa:0};var k=a.ua;k&&(a.W.style[k]=a.$.style[k]="translate("+a.o.wa+"px,"+a.o.Aa+"px)");a.Ba.Hg||(a.W.style.willChange=a.$.style.willChange="");k=cx(a,!0);for(var l in a.H)a.H[l].Qb(b,a.T,h,f,g,e,{wa:k.width,Aa:k.height},
{kl:d,Md:!0,timestamp:c})},ex=function(a,b,c,d){this.H=a;this.T=d;this.o=c;this.i=null;this.$=!1;this.j=null;this.W=!0;this.ha=b},gx=function(a,b,c){b=a.o.ye(b);a.i&&c?fx(a,a.ha(cx(a.H,!0),a.i,b,_.n())):fx(a,ax(b))},hx=function(a,b){a.o=b;!a.j&&a.i&&(b=a.o.ye(a.i),b.center==a.i.center&&b.zoom==a.i.zoom&&b.heading==a.i.heading&&b.tilt==a.i.tilt||fx(a,ax(b)))},ix=function(a){a.$||(a.$=!0,_.Vn(function(b){a.$=!1;if(a.j){var c=a.j,d=c.ac(b),e=d.Zc;d=d.done;0==d&&(a.j=null,c.tc());e?a.i=e=a.o.ye(e):e=
a.i;e&&(0==d&&a.W?dx(a.H,e,b,!1):(a.H.Qb(e,b,c.Kb),1!=d&&0!=d||ix(a)));e&&!c.Kb&&a.T(e)}else a.i&&dx(a.H,a.i,b,!0);a.W=!1}))},fx=function(a,b){a.j&&a.j.tc();a.j=b;a.W=!0;(b=b.Kb)&&a.T(a.o.ye(b.vb));ix(a)},jx=function(a,b){this.Kb=a;this.i=b},kx=function(a,b,c,d){var e=a.zoom-b.zoom,f=a.zoom;f=-.1>e?Math.floor(f):.1<e?Math.ceil(f):Math.round(f);e=d+1E3*Math.sqrt(Math.hypot(a.center.Ca-b.center.Ca,a.center.Da-b.center.Da)*Math.pow(2,a.zoom)/c)/3.2;var g=d+1E3*(.5-Math.abs(a.zoom%1-.5))/2;this.Yb=(0>=
c?g:Math.max(g,e))-d;d=0>=c?0:(a.center.Ca-b.center.Ca)/c;b=0>=c?0:(a.center.Da-b.center.Da)/c;this.i=.5*this.Yb*d;this.j=.5*this.Yb*b;this.o=a;this.vb={center:_.Nm(a.center,new _.ag(this.Yb*d/2,this.Yb*b/2)),heading:a.heading,tilt:a.tilt,zoom:f};this.Ef=[]},lx=function(a,b,c,d){this.j=b;this.H=c;this.T=d;this.o=a;this.i=[];this.Kb=void 0},mx=function(a,b){a.o=b;a.H();var c=_.ql?_.z.performance.now():(0,_.nc)();0<a.i.length&&10>c-a.i.slice(-1)[0].Ed||(a.i.push({Ed:c,Zc:b}),10<a.i.length&&a.i.splice(0,
1))},nx=function(a,b,c){var d=_.eg(a.zoom,a.tilt,a.heading),e=_.eg(b,a.tilt,a.heading);return{center:_.Nm(c,_.fg(e,_.Um(d,_.Om(a.center,c)))),zoom:b,heading:a.heading,tilt:a.tilt}},ox=function(a,b,c){var d=this;this.o=a(function(){ix(d.i)});this.i=new ex(this.o,b,{ye:_.na(),wf:function(){return{min:0,max:1E3}}},function(e){return c(e,d.o.getBounds(e))});this.H=b;this.j=_.Vk},Hv=function(a,b,c,d){d=void 0===d?_.n():d;var e=a.i.wf(),f=a.i.i;b=Math.min(b,e.max);b=Math.max(b,e.min);f&&(b=nx(f,b,c),d=
a.H(cx(a.o,!0),f,b,d),fx(a.i,d))},px=function(a,b){var c=a.i.i;if(!c)return null;b=new lx(c,b,function(){ix(a.i)},function(d){fx(a.i,d)});fx(a.i,b);return b},qx=function(a,b,c){c=void 0===c?{}:c;var d=0!=c.nk,e=!!c.Hg;return new ox(function(f){return new bx(a,f,{Hg:e})},function(f,g,h,k){return new $w(new Yw(f,g,h),{tc:k,maxDistance:d?1.5:0})},b)},sx=function(a,b){this.i=a;this.j=b;rx(this)},rx=function(a){var b=null,c=a.get("restriction");c&&_.Cj(a.j,"Mbr");var d=a.get("projection");if(c){b=_.Qn(c.latLngBounds.getSouthWest(),
d);var e=_.Qn(c.latLngBounds.getNorthEast(),d);b={min:new _.ag(_.Jm(c.latLngBounds.Va)?-Infinity:b.Ca,e.Da),max:new _.ag(_.Jm(c.latLngBounds.Va)?Infinity:e.Ca,b.Da)};e=1==c.strictBounds}c=new _.cu(a.get("minZoom")||0,a.get("maxZoom")||30);d=a.get("mapTypeMinZoom");var f=a.get("mapTypeMaxZoom"),g=a.get("trackerMaxZoom");_.le(d)&&(c.min=Math.max(c.min,d));_.le(g)?c.max=Math.min(c.max,g):_.le(f)&&(c.max=Math.min(c.max,f));_.ze(function(h){return h.min<=h.max},"minZoom cannot exceed maxZoom")(c);d=a.i.Mg();
e=new Ww(b,c,{width:d.width,height:d.height},e);hx(a.i.i,e);a.set("zoomRange",c);a.set("boundsRange",b)},tx=_.oa("j"),ux=function(a,b){function c(d){var e=b.getAt(d);if(e instanceof _.nj){d=e.get("styles");var f=Sw(d);e.Pb=function(g){var h=g?"hybrid"==e.i?"":"p.s:-60|p.l:-60":f,k=nw(a,e.i);return(new Yv(k,h,null,null,null,null)).Pb(g)}}}_.L.addListener(b,"insert_at",c);_.L.addListener(b,"set_at",c);b.forEach(function(d,e){return c(e)})},vx=function(a){var b=this;this.i=a;a.addListener(function(){return b.notify("style")})},
wx=function(a,b,c){_.de(_.Lk,function(d,e){b.set(e,nw(a,e,{Gk:c}))})},xx=function(a,b){function c(e){switch(e.mapTypeId){case "roadmap":return"Tm";case "satellite":return e.ma?"Ta":"Tk";case "hybrid":return e.ma?"Ta":"Th";case "terrain":return"Tr";default:return"To"}}_.L.kb(b,"basemaptype_changed",function(){var e=b.get("baseMapType");e&&_.Cj(a,c(e))});var d=a.__gm;_.L.kb(d,"hascustomstyles_changed",function(){if(d.get("hasCustomStyles")){_.Cj(a,"Ts");var e=d.get("apistyle");e&&_.K("stats").then(function(f){f.Ra(e)})}})},
yx=function(a){if(a&&_.Ko(a.getDiv())&&_.Fo()){_.Cj(a,"Tdev");var b=document.querySelector('meta[name="viewport"]');(b=b&&b.content)&&b.match(/width=device-width/)&&_.Cj(a,"Mfp")}},zx=function(){var a=new Pv(Sv()),b={};b.obliques=new Pv(Tv());b.report_map_issue=a;return b},Ax=function(a){var b=a.get("embedReportOnceLog");if(b){var c=function(){for(;b.getLength();){var d=b.pop();_.Cj(a,d)}};_.L.addListener(b,"insert_at",c);c()}else _.L.addListenerOnce(a,"embedreportoncelog_changed",function(){Ax(a)})},
Bx=function(a){var b=a.get("embedFeatureLog");if(b){var c=function(){for(;b.getLength();){var d=b.pop();_.Wo(a,d)}};_.L.addListener(b,"insert_at",c);c()}else _.L.addListenerOnce(a,"embedfeaturelog_changed",function(){Bx(a)})},Cx=function(a,b,c){function d(){var q=Cx.i(a.getDiv());q.width-=e;q.width=Math.max(1,q.width);q.height-=f;q.height=Math.max(1,q.height);var r=a.getProjection();q=Cx.j(r,b,q);var u=Cx.o(b,r);if(_.le(q)&&u){var v=_.fg(_.eg(q,a.getTilt()||0,a.getHeading()||0),{wa:g/2,Aa:h/2});u=
_.Om(_.Qn(u,r),v);u=_.Rn(u,r);a.setCenter(u);a.setZoom(q)}}var e=80,f=80,g=0,h=0;if("number"===typeof c)e=f=2*c-.01;else if(c){var k=c.left||0,l=c.right||0,m=c.bottom||0;c=c.top||0;e=k+l-.01;f=c+m-.01;h=c-m;g=k-l}a.getProjection()?d():_.L.addListenerOnce(a,"projection_changed",d)},Dx=_.n();_.A(Av,_.C);Av.prototype.getTile=function(){return new _.Xs(this.V[1])};Av.prototype.i=function(){return new _.Xs(_.G(this,1))};
var Qw={hue:"h",saturation:"s",lightness:"l",gamma:"g",invert_lightness:"il",visibility:"v",color:"c",weight:"w"},Nw={all:0,administrative:1,"administrative.country":17,"administrative.province":18,"administrative.locality":19,"administrative.neighborhood":20,"administrative.land_parcel":21,poi:2,"poi.business":33,"poi.government":34,"poi.school":35,"poi.medical":36,"poi.attraction":37,"poi.place_of_worship":38,"poi.sports_complex":39,"poi.park":40,road:3,"road.highway":49,"road.highway.controlled_access":785,
"road.arterial":50,"road.local":51,transit:4,"transit.line":65,"transit.station":66,"transit.station.rail":1057,"transit.station.bus":1058,"transit.station.airport":1059,"transit.station.ferry":1060,landscape:5,"landscape.man_made":81,"landscape.man_made.building":1297,"landscape.man_made.business_corridor":1299,"landscape.natural":82,"landscape.natural.landcover":1313,"landscape.natural.terrain":1314,water:6},Ow={"poi.business.shopping":529,"poi.business.food_and_drink":530,"poi.business.gas_station":531,
"poi.business.car_rental":532,"poi.business.lodging":533,"landscape.man_made.business_corridor":1299,"landscape.man_made.building":1297},Pw={all:"",geometry:"g","geometry.fill":"g.f","geometry.stroke":"g.s",labels:"l","labels.icon":"l.i","labels.text":"l.t","labels.text.fill":"l.t.f","labels.text.stroke":"l.t.s"};Bv.prototype.addListener=function(a,b){this.Ga.addListener(a,b)};Bv.prototype.addListenerOnce=function(a,b){this.Ga.addListenerOnce(a,b)};
Bv.prototype.removeListener=function(a,b){this.Ga.removeListener(a,b)};Iv.prototype.xd=function(a,b){var c=this;b.stop();this.i||(this.j&&_.or(this.j,!0),(b=px(this.o,function(){c.i=null;c.H.reset()}))?this.i={origin:a.Gb,Zm:this.o.i.i.zoom,Je:b}:this.H.reset())};Iv.prototype.qe=function(a){if(this.i){var b=this.o.i.i;mx(this.i.Je,{center:b.center,zoom:this.i.Zm+(a.Gb.clientY-this.i.origin.clientY)/128,heading:b.heading,tilt:b.tilt})}};
Iv.prototype.Pd=function(){this.j&&_.or(this.j,!1);this.i&&this.i.Je.release();this.i=null};Jv.prototype.xd=function(a,b){var c=this,d=!this.i&&1==b.button&&1==a.Kf,e=this.H(d?2:4);"none"==e||"cooperative"==e&&d||(b.stop(),this.i?this.i.Qf=Kv(this,a):(this.o&&_.or(this.o,!0),(b=px(this.j,function(){c.i=null;c.T.reset()}))?this.i={Qf:Kv(this,a),Je:b}:this.T.reset()))};
Jv.prototype.qe=function(a){if(this.i){var b=this.H(4);if("none"!=b){var c=this.j.i.i;b="zoomaroundcenter"==b&&1<a.Kf?c.center:_.Om(_.Nm(c.center,this.i.Qf.Gb),this.j.Tc(a.Gb));mx(this.i.Je,{center:b,zoom:this.i.Qf.zoom+Math.log(a.radius/this.i.Qf.radius)/Math.LN2,heading:c.heading,tilt:c.tilt})}}};Jv.prototype.Pd=function(){this.H(3);this.o&&_.or(this.o,!1);this.i&&this.i.Je.release();this.i=null};_.Ea(Pv,_.M);
Pv.prototype.changed=function(a){if("available"!=a){"featureRects"==a&&Cv(this.i);a=this.get("viewport");var b=this.get("featureRects");a=this.j(a,b);null!=a&&a!=this.get("available")&&this.set("available",a)}};_.Ea(Xv,_.kj);Xv.prototype.Pb=function(a){return this.T(this,void 0===a?!1:a)};Xv.prototype.kc=_.qa("j");_.Ea(Yv,Xv);$v.prototype.Eb=_.qa("i");$v.prototype.sc=function(){return _.jb(this.j,function(a){return a.sc()})};
$v.prototype.release=function(){for(var a=_.Aa(this.j),b=a.next();!b.done;b=a.next())b.value.release();this.o()};aw.prototype.Zb=function(a,b){b=void 0===b?{}:b;var c=_.Oc("DIV"),d=_.im(this.i,function(e,f){e=e.Zb(a);var g=e.Eb();g.style.position="absolute";g.style.zIndex=f;c.appendChild(g);return e});return new $v(c,d,this.Wa.size,this.j,{Mb:b.Mb})};cw.prototype.Eb=function(){return this.j.Eb()};cw.prototype.sc=function(){return!this.H&&this.j.sc()};cw.prototype.release=function(){this.j.release()};
dw.prototype.Zb=function(a,b){a=new _.Ft(a,this.$,_.Oc("DIV"),{errorMessage:"Przepraszamy, nie mamy zdj\u0119\u0107 tego miejsca.",Mb:b&&b.Mb,Ri:this.W||void 0});return new cw(a,this.j,this.ha,this.o,this.i,this.Wa,this.H,this.T)};var Ex=[{ag:108.25,$f:109.625,eg:49,dg:51.5},{ag:109.625,$f:109.75,eg:49,dg:50.875},{ag:109.75,$f:110.5,eg:49,dg:50.625},{ag:110.5,$f:110.625,eg:49,dg:49.75}];
ew.prototype.Zb=function(a,b){a:{var c=a.La;if(!(7>c)){var d=1<<c-7;c=a.Ea/d;d=a.Fa/d;for(var e=_.Aa(Ex),f=e.next();!f.done;f=e.next())if(f=f.value,c>=f.ag&&c<=f.$f&&d>=f.eg&&d<=f.dg){c=!0;break a}}c=!1}return c?this.i.Zb(a,b):this.j.Zb(a,b)};ow.prototype.o=function(a){var b=this;clearTimeout(this.H);1==a?(pw(this,!0),this.H=setTimeout(function(){return qw(b)},1500)):2==a?pw(this,!1):3==a?qw(this):4==a&&(this.i.style.transitionDuration="0.2s",this.i.style.opacity=0)};Cw.prototype.H=function(a){return this.T(this.j.H(a))};
Cw.prototype.o=function(a){return this.T(this.j.o(a))};Cw.prototype.i=function(){return this.j.i()};_.A(Fw,_.M);_.t=Fw.prototype;_.t.mapTypeId_changed=function(){var a=this.get("mapTypeId");this.jf(a)};_.t.heading_changed=function(){var a=this.get("heading");if("number"===typeof a){var b=_.ge(90*Math.round(a/90),0,360);a!=b?this.set("heading",b):(a=this.get("mapTypeId"),this.jf(a))}};_.t.tilt_changed=function(){var a=this.get("mapTypeId");this.jf(a)};
_.t.setMapTypeId=function(a){this.jf(a);this.set("mapTypeId",a)};
_.t.jf=function(a){var b=this.get("heading")||0,c=this.o.get(a),d=this.get("tilt");if(this.get("tilt")&&c&&c instanceof Xv&&c.i&&c.i[b])c=c.i[b];else if(0==d&&0!=b){this.set("heading",0);return}c&&c==this.T||(this.j&&(_.L.removeListener(this.j),this.j=null),b=(0,_.y)(this.jf,this,a),a&&(this.j=_.L.addListener(this.o,a.toLowerCase()+"_changed",b)),c&&c instanceof _.nj?(a=c.i,this.set("styles",c.get("styles")),this.set("baseMapType",this.o.get(a))):(this.set("styles",null),this.set("baseMapType",c)),
this.set("maxZoom",c&&c.maxZoom),this.set("minZoom",c&&c.minZoom),this.T=c)};_.t.rk=function(a,b,c,d,e,f,g){if(void 0==f)return null;if(d instanceof Xv){a=new Yv(d,a,b,e,c,g);if(b=this.i instanceof Yv)if(b=this.i,b==a)b=!0;else if(b&&a){if(c=b.heading==a.heading&&b.projection==a.projection&&b.De==a.De)b=b.j.get(),c=a.j.get(),c=b==c?!0:b&&c?b.scale==c.scale&&b.Yc==c.Yc&&(b.jc==c.jc?!0:b.jc&&c.jc?b.jc.equals(c.jc):!1):!1;b=c}else b=!1;b||(this.i=a)}else this.i=d;return this.i};_.A(Hw,_.M);
Hw.prototype.changed=function(a){if("maxZoomRects"==a||"latLng"==a){a=this.get("latLng");var b=this.get("maxZoomRects");if(a&&b){for(var c=void 0,d=0,e;e=b[d++];)e.bounds.contains(a)&&(c=Math.max(c||0,e.maxZoom));a=c;a!=this.get("maxZoom")&&this.set("maxZoom",a)}else void 0!=this.get("maxZoom")&&this.set("maxZoom",void 0)}};_.Ea(Mw,_.M);
Mw.prototype.getBounds=function(){var a=this.map.get("center"),b=this.map.get("zoom");if(a&&null!=b){var c=this.map.get("tilt")||0,d=this.map.get("heading")||0;var e=this.map.getProjection();a={center:_.Qn(a,e),zoom:b,tilt:c,heading:d};a=this.rb.ug(a);b=!1;b=void 0===b?!0:b;e=_.Pn(e);e=new _.vf(e.fromPointToLatLng(new _.O(a.min.Ca,a.max.Da),!b),e.fromPointToLatLng(new _.O(a.max.Ca,a.min.Da),!b))}else e=null;return e};var Rw=/^#[0-9a-fA-F]{6}$/;_.A(Tw,_.M);
Tw.prototype.changed=function(a){if("apistyle"!=a&&"hasCustomStyles"!=a){var b=this.get("mapTypeStyles")||this.get("styles");this.set("hasCustomStyles",_.ce(b));a=[];_.xh[13]&&a.push({featureType:"poi.business",elementType:"labels",stylers:[{visibility:"off"}]});_.ke(a,b);b=this.get("uDS")?"hybrid"==this.get("mapTypeId")?"":"p.s:-60|p.l:-60":Sw(a);b!=this.i&&(this.i=b,this.notify("apistyle"));a.length&&(!b||1E3<b.length)&&_.Rf(_.hm(_.L.trigger,this,"styleerror",b.length))}};
Tw.prototype.getApistyle=_.qa("i");Uw.prototype.$=function(a){if(_.Hc(a,0)){this.T={};this.j={};for(var b=0;b<_.Hc(a,0);++b){var c=new Av(_.Gc(a,0,b)),d=c.getTile(),e=d.getZoom(),f=d.Qc();d=d.Rc();c=_.Ac(c,2);var g=this.T;g[e]=g[e]||{};g[e][f]=g[e][f]||{};g[e][f][d]=c;this.j[e]=Math.max(this.j[e]||0,c)}Cv(this.W)}};Uw.prototype.H=function(a){var b=this.T,c=a.Ea,d=a.Fa;a=a.La;return b[a]&&b[a][c]&&b[a][c][d]||0};Uw.prototype.o=function(a){return this.j[a]||0};Uw.prototype.i=_.qa("W");
Ww.prototype.ye=function(a){var b=a.center,c=a.zoom,d=a.heading;a=a.tilt;c=Vw(c,this.i.min,this.i.max);if(!this.j||!this.o.width||!this.o.height)return{center:b,zoom:c,heading:d,tilt:a};var e=this.o.width/Math.pow(2,c),f=this.o.height/Math.pow(2,c);b=new _.ag(Vw(b.Ca,this.j.min.Ca+e/2,this.j.max.Ca-e/2),Vw(b.Da,this.j.min.Da+f/2,this.j.max.Da-f/2));return{center:b,zoom:c,heading:d,tilt:a}};Ww.prototype.wf=function(){return{min:this.i.min,max:this.i.max}};
Yw.prototype.ac=function(a){if(0>=a)return this.i;if(a>=this.Yb)return this.vb;a/=this.Yb;var b=this.j?Math.expm1(a*Math.log1p(this.j))/this.j:a;return{center:new _.ag(this.i.center.Ca*(1-b)+this.vb.center.Ca*b,this.i.center.Da*(1-b)+this.vb.center.Da*b),zoom:this.i.zoom*(1-a)+this.vb.zoom*a,heading:this.o*(1-a)+this.vb.heading*a,tilt:this.i.tilt*(1-a)+this.vb.tilt*a}};
$w.prototype.ac=function(a){a=void 0===a?0:a;if(!this.i){var b=this.j,c=this.Kb.Yb;this.i=a+(c<b.o?Math.acos(1-c/b.j*b.i)/b.i:b.H+(c-b.o)/b.j);return{done:1,Zc:this.Kb.ac(0)}}a>=this.i?a={done:0,Zc:this.Kb.vb}:(b=this.j,a=this.i-a,a={done:1,Zc:this.Kb.ac(this.Kb.Yb-(a<b.H?(1-Math.cos(a*b.i))*b.j/b.i:b.o+b.j*(a-b.H)))});return a};
bx.prototype.getBounds=function(a,b){var c=void 0===b?{}:b,d=void 0===c.top?0:c.top;b=void 0===c.left?0:c.left;var e=void 0===c.bottom?0:c.bottom;c=void 0===c.right?0:c.right;var f=cx(this,!0);b-=f.width/2;c=f.width/2-c;b>c&&(b=c=(b+c)/2);var g=d-f.height/2;e=f.height/2-e;g>e&&(g=e=(g+e)/2);if(this.j){var h={wa:f.width,Aa:f.height},k=a.center,l=a.zoom,m=a.tilt;a=a.heading;b+=f.width/2;c+=f.width/2;g+=f.height/2;e+=f.height/2;f=this.j.j(b,g,k,l,m,a,h);d=this.j.j(b,e,k,l,m,a,h);b=this.j.j(c,g,k,l,m,
a,h);c=this.j.j(c,e,k,l,m,a,h)}else h=_.eg(a.zoom,a.tilt,a.heading),f=_.Nm(a.center,_.fg(h,{wa:b,Aa:g})),d=_.Nm(a.center,_.fg(h,{wa:c,Aa:g})),c=_.Nm(a.center,_.fg(h,{wa:c,Aa:e})),b=_.Nm(a.center,_.fg(h,{wa:b,Aa:e}));return{min:new _.ag(Math.min(f.Ca,d.Ca,c.Ca,b.Ca),Math.min(f.Da,d.Da,c.Da,b.Da)),max:new _.ag(Math.max(f.Ca,d.Ca,c.Ca,b.Ca),Math.max(f.Da,d.Da,c.Da,b.Da))}};
bx.prototype.Qb=function(a,b,c){var d=a.center,e=_.eg(a.zoom,a.tilt,a.heading,this.j),f=!e.equals(this.i&&this.i.scale);this.i={scale:e,center:d};if((f||this.j)&&this.o)this.T=_.fg(e,_.Tm(_.Um(e,_.Nm(d,_.fg(e,this.o)))));else if(this.o=_.Tm(_.Um(e,_.Om(this.T,d))),d=this.ua)this.W.style[d]=this.$.style[d]="translate("+this.o.wa+"px,"+this.o.Aa+"px)",this.W.style.willChange=this.$.style.willChange="transform";d=_.Om(this.T,_.fg(e,this.o));f=this.getBounds(a);var g=cx(this,!0),h;for(h in this.H)this.H[h].Qb(f,
this.T,e,a.heading,a.tilt,d,{wa:g.width,Aa:g.height},{kl:!0,Md:!1,Kb:c,timestamp:b})};ex.prototype.wf=function(){return this.o.wf()};jx.prototype.tc=_.n();jx.prototype.ac=function(a){a-=this.i;return{Zc:this.Kb.ac(a),done:a<this.Kb.Yb?1:0}};kx.prototype.ac=function(a){if(a>=this.Yb)return this.vb;a=Math.min(1,1-a/this.Yb);return{center:_.Om(this.vb.center,new _.ag(this.i*a*a*a,this.j*a*a*a)),zoom:this.vb.zoom-a*(this.vb.zoom-this.o.zoom),tilt:this.vb.tilt,heading:this.vb.heading}};
lx.prototype.tc=function(){this.j&&(this.j(),this.j=null)};lx.prototype.ac=function(){return{Zc:this.o,done:this.j?2:0}};lx.prototype.release=function(){var a=_.ql?_.z.performance.now():(0,_.nc)();if(!(0>=this.i.length)){var b=this.i.slice(-1)[0],c=yv(this.i,function(d){return 125>a-d.Ed});c=0>c?b:this.i[c];this.T(new jx(new kx(b.Zc,c.Zc,b.Ed-c.Ed,a),a))}};_.t=ox.prototype;_.t.yc=function(a){var b=this.o,c=_.Sa(a);if(!b.H[c]){if("function"===typeof a.lb){var d=a.lb();d&&(b.j=d,b.ma=c)}b.H[c]=a;b.va()}};
_.t.fe=function(a){var b=this.o,c=_.Sa(a);b.H[c]&&(c===b.ma&&(b.j=void 0,b.ma=void 0),a.dispose(),delete b.H[c])};_.t.Mg=function(){return cx(this.o)};_.t.Tc=function(a){var b=this.o,c=cx(b,void 0);if(b.i){var d={wa:c.width,Aa:c.height};a=b.j?b.j.j(a.clientX-c.left,a.clientY-c.top,b.i.center,_.Vm(b.i.scale),b.i.scale.tilt,b.i.scale.heading,d):_.Nm(b.i.center,_.fg(b.i.scale,{wa:a.clientX-(c.left+c.right)/2,Aa:a.clientY-(c.top+c.bottom)/2}))}else a=new _.ag(0,0);return a};
_.t.Pl=function(a){var b=this.o;if(b.i){var c=cx(b);b.j?(a=b.j.i(a,b.i.center,_.Vm(b.i.scale),b.i.scale.tilt,b.i.scale.heading,{wa:c.width,Aa:c.height}),c={clientX:c.left+a[0],clientY:c.top+a[1]}):(a=_.Um(b.i.scale,_.Om(a,b.i.center)),c={clientX:(c.left+c.right)/2+a.wa,clientY:(c.top+c.bottom)/2+a.Aa})}else c={clientX:0,clientY:0};return c};_.t.ug=function(a,b){return this.o.getBounds(a,b)};_.t.Ng=function(){ix(this.i)};_.t.Jf=function(a,b){gx(this.i,a,b)};_.A(sx,_.M);
sx.prototype.changed=function(a){"zoomRange"!=a&&"boundsRange"!=a&&rx(this)};_.A(tx,_.M);tx.prototype.immutable_changed=function(){var a=this,b=a.get("immutable"),c=a.i;b!=c&&(_.de(a.j,function(d){(c&&c[d])!==(b&&b[d])&&a.set(d,b&&b[d])}),a.i=b)};_.Ea(vx,_.M);vx.prototype.changed=function(a){"tileMapType"!=a&&"style"!=a&&this.notify("style")};
vx.prototype.getStyle=function(){var a=[],b=this.get("tileMapType");if(b instanceof Xv&&(b=b.__gmsd)){var c=new _.zn;c.V[0]=b.type;if(b.params)for(var d in b.params){var e=_.An(c);_.yn(e,d);var f=b.params[d];f&&(e.V[1]=f)}a.push(c)}d=new _.zn;d.V[0]=37;_.yn(_.An(d),"smartmaps");a.push(d);this.i.get().forEach(function(g){g.styler&&a.push(g.styler)});return a};Cx.i=_.Th;
Cx.j=function(a,b,c){var d=b.getSouthWest();b=b.getNorthEast();var e=d.lng(),f=b.lng();e>f&&(d=new _.I(d.lat(),e-360,!0));d=a.fromLatLngToPoint(d);b=a.fromLatLngToPoint(b);a=Math.max(d.x,b.x)-Math.min(d.x,b.x);d=Math.max(d.y,b.y)-Math.min(d.y,b.y);return a>c.width||d>c.height?0:Math.floor(Math.min(_.nn(c.width+1E-12)-_.nn(a+1E-12),_.nn(c.height+1E-12)-_.nn(d+1E-12)))};Cx.o=function(a,b){a=_.po(b,a,0);return _.no(b,new _.O((a.Ma+a.Qa)/2,(a.Ja+a.Pa)/2),0)};Dx.prototype.j=function(a,b,c,d,e,f){var g=_.Pd(_.Qd(_.H)),h=a.__gm,k=a.getDiv();if(k){_.L.addDomListenerOnce(c,"mousedown",function(){_.Cj(a,"Mi")},!0);var l=new _.qu({Xd:c,di:k,Wh:!0,Ci:_.yc(_.Qd(_.H),15),backgroundColor:b.backgroundColor,yh:!0,rl:1==_.yj.type,tl:!0}),m=l.i,q=new _.M;_.Ro(l.H,0);h.set("panes",l.ve);h.set("innerContainer",l.o);var r=new Hw,u=zx(),v,x,w=_.Ac(_.ae(),14);k=sv();var E=0<k?k:w,J=a.get("noPerTile")&&_.xh[15];(k=b.mapId||null)&&_.Cj(a,"MId");(function(){var ea=new Uw;v=
Dw(ea,w,a,J,E);x=new _.hu(g,r,u,J?null:ea)})();x.bindTo("tilt",a);x.bindTo("heading",a);x.bindTo("bounds",a);x.bindTo("zoom",a);var N=new fw(new _.Ud(_.G(_.H,1)),_.ae(),_.Qd(_.H),a,v,u.obliques,!!k);wx(N,a.mapTypes,b.enableSplitTiles);h.set("eventCapturer",l.T);h.set("panBlock",l.W);var R=_.xg(!1),pa=Gw(a,R);x.bindTo("baseMapType",pa);N=h.Wd=pa.H;var ra=_.xg(!1),gb=Ov({draggable:_.nr(a,"draggable"),xk:_.nr(a,"gestureHandling"),Cf:ra}),Od=!_.xh[20]||0!=a.get("animatedZoom"),yd=null,g6=function(){_.K("util").then(function(ea){ea.j.i();
setTimeout(function(){return _.Aq(ea.i,1)},_.Cm(_.H,38)?_.Ac(_.H,38):5E3);ea.H(a)})},zA=!1,lj=null,Hq=new Mw(a,function(ea){return qx(l,ea,{nk:Od})}),Ic=Hq.rb,h6=new _.Tt(function(ea,$a){ea=new _.go(m,0,Ic,_.ao(ea),$a,{Pe:!0});Ic.yc(ea);return ea},function(ea){a.get("tilesloading")!=ea&&a.set("tilesloading",ea);ea||(yd&&yd(),zA||(zA=!0,g6(),d&&d.i&&_.Ai(d.i),lj&&(Ic.fe(lj),lj=null),f&&(f.done("wmb","wmc"),d&&d.get("loading")&&f.done("smb"))),_.L.trigger(a,"tilesloaded"))}),mj=_.Qh();Jw(k,mj,a,h);
h.lb(!1);var jP=null;pa.H.kb(function(ea){jP!=ea&&(jP=ea,_.Vt(h6,ea))});h.set("cursor",a.get("draggableCursor"));new tw(a,Ic,l,gb);mj=_.nr(a,"draggingCursor");var i6=_.nr(h,"cursor"),j6=new ow(h.get("panBlock")),k6=Lv(Ic,l,new _.pr(l.o,mj,i6),function(ea){var $a=gb.get();j6.o("cooperative"==$a?ea:4);return $a},{Yf:!0,ii:function(){return!a.get("disableDoubleClickZoom")},hj:function(){return a.get("scrollwheel")}});gb.kb(function(ea){k6.Rd("cooperative"==ea||"none"==ea)});e({map:a,rb:Ic,Wd:N,ve:l.ve});
h.T.then(function(ea){ea||_.K("onion").then(function($a){$a.i(a,v)})});_.xh[35]&&(Ax(a),Bx(a));var yg=new _.du;yg.bindTo("tilt",a);yg.bindTo("zoom",a);yg.bindTo("mapTypeId",a);yg.bindTo("aerial",u.obliques,"available");h.T.then(function(ea){(yg.i=ea)&&yg.Ke()});h.bindTo("tilt",yg,"actualTilt");_.L.addListener(x,"attributiontext_changed",function(){a.set("mapDataProviders",x.get("attributionText"))});if(!k){var Ah=new Tw;_.K("util").then(function(ea){ea.i.i(function(){R.set(!0);Ah.set("uDS",!0)})});
Ah.bindTo("styles",a);Ah.bindTo("mapTypeId",pa);Ah.bindTo("mapTypeStyles",pa,"styles");h.bindTo("apistyle",Ah);h.bindTo("hasCustomStyles",Ah);_.L.forward(Ah,"styleerror",a)}e=new vx(h.j);e.bindTo("tileMapType",pa);h.bindTo("style",e);var Iq=new _.qp(a,Ic,function(){h.set("pixelBounds",zv(Iq))}),l6=Iq;Ic.yc(Iq);h.set("projectionController",Iq);h.set("mouseEventTarget",{});(new _.tu(_.yj.j,l.o)).bindTo("title",h);d&&(d.o.kb(function(){var ea=d.o.get();lj||!ea||zA||(lj=new _.Un(m,-1,ea),d.i&&_.Ai(d.i),
Ic.yc(lj))}),d.bindTo("tilt",h),d.bindTo("size",h));h.bindTo("zoom",a);h.bindTo("center",a);h.bindTo("size",q);h.bindTo("baseMapType",pa);a.set("tosUrl",_.Mu);e=new tx({projection:1});e.bindTo("immutable",h,"baseMapType");mj=new _.ru({projection:new _.qh});mj.bindTo("projection",e);a.bindTo("projection",mj);var BA=function(ea,$a,Kb){var Ff=a.getCenter(),AA=a.getZoom(),kP=a.getProjection();if(Ff&&null!=AA&&kP){var lP=a.getTilt()||0,mP=a.getHeading()||0,m6=_.eg(AA,lP,mP);Ic.Jf({center:_.Nm(_.Qn(Ff,
kP),_.fg(m6,{wa:ea,Aa:$a})),zoom:AA,heading:mP,tilt:lP},Kb)}};_.L.addListener(h,"panby",function(ea,$a){BA(ea,$a,!0)});_.L.addListener(h,"panbynow",function(ea,$a){BA(ea,$a,!1)});_.L.addListener(h,"panbyfraction",function(ea,$a){var Kb=Ic.Mg();ea*=Kb.right-Kb.left;$a*=Kb.bottom-Kb.top;BA(ea,$a,!0)});_.L.addListener(h,"pantolatlngbounds",function(ea,$a){_.Nt(a,Ic,ea,$a)});_.L.addListener(h,"panto",function(ea){if(ea instanceof _.I){var $a=a.getCenter(),Kb=a.getZoom(),Ff=a.getProjection();$a&&null!=
Kb&&Ff?(ea=_.Qn(ea,Ff),$a=_.Qn($a,Ff),Kb={center:_.Sm(Hq.rb.j,ea,$a),zoom:Kb,heading:a.getHeading()||0,tilt:a.getTilt()||0},Hq.rb.Jf(Kb,!0),Hq.o()):a.setCenter(ea)}else throw Error("panTo: latLng must be of type LatLng");});var Gf=new sx(Ic,a);Gf.bindTo("mapTypeMaxZoom",pa,"maxZoom");Gf.bindTo("mapTypeMinZoom",pa,"minZoom");Gf.bindTo("maxZoom",a);Gf.bindTo("minZoom",a);Gf.bindTo("trackerMaxZoom",r,"maxZoom");Gf.bindTo("restriction",a);Gf.bindTo("projection",a);var nP=new _.su(_.Ko(c));h.bindTo("fontLoaded",
nP);e=h.ha;e.bindTo("scrollwheel",a);e.bindTo("disableDoubleClickZoom",a);e=function(){var ea=a.get("streetView");ea?(a.bindTo("svClient",ea,"client"),ea.__gm.bindTo("fontLoaded",nP)):(a.unbind("svClient"),a.set("svClient",null))};e();_.L.addListener(a,"streetview_changed",e);a.i||(yd=function(){yd=null;Promise.all([_.K("controls"),h.T]).then(function(ea){var $a=_.Aa(ea);ea=$a.next().value;$a=$a.next().value;var Kb=new ea.Ih(l.H);h.set("layoutManager",Kb);ea.Fl(Kb,a,pa,l.H,x,u.report_map_issue,Gf,
yg,c,ra,l6,Ic,$a);ea.Gl(a,l.o);ea.zh(c)})},_.Cj(a,"Mm"),b.v2&&_.Cj(a,"Mz"),_.Xo("Mm","-p",a),xx(a,pa),yx(a));b=new fw(new _.Ud(_.G(_.H,1)),_.ae(),_.Qd(_.H),a,new Cw(v,function(ea){return J?E:ea||w}),u.obliques,!!k);ux(b,a.overlayMapTypes);new Bw(_.hm(_.Cj,a),l.ve.mapPane,a.overlayMapTypes,Ic,N,R);_.xh[35]&&h.bindTo("card",a);_.xh[15]&&h.bindTo("authUser",a);var oP=0,pP=0,qP=function(){var ea=l.H,$a=ea.clientWidth;ea=ea.clientHeight;if(oP!=$a||pP!=ea){oP=$a;pP=ea;if(Ic){var Kb=Ic.i,Ff=Kb.H;Ff.ha=null;
Ff.va();Kb.j&&Kb.j.Kb?Kb.T(Kb.o.ye(Kb.j.Kb.vb)):Kb.i&&Kb.T(Kb.i)}q.set("size",new _.P($a,ea));rx(Gf)}},Bh=document.createElement("iframe");Bh.setAttribute("aria-hidden","true");Bh.frameBorder="0";Bh.tabIndex=-1;Bh.style.cssText="z-index: -1; position: absolute; width: 100%;height: 100%; top: 0; left: 0; border: none";_.L.addDomListener(Bh,"load",function(){qP();_.L.addDomListener(Bh.contentWindow,"resize",qP)});l.H.appendChild(Bh)}};Dx.prototype.fitBounds=Cx;
Dx.prototype.i=function(a,b,c,d,e){a=new _.Ft(a,b,c,{});a.setUrl(d).then(e);return a};_.cf("map",new Dx);});
